# Generated by Django 5.2 on 2025-05-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('domicilio', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('vehiculo', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3)),
                ('disponibilidad', models.CharField(max_length=255)),
                ('terminos_aceptados', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tramite', models.TextField()),
                ('terminos_aceptados', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cadete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadeteush.inscripcion')),
            ],
        ),
    ]
